apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutating-webhook-akash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutating-webhook
  template:
    metadata:
      labels:
        app: mutating-webhook
    spec:
      containers:
      - name: mutating-webhook
        image: eu.gcr.io/uai-production/registry.understand.ai/infrastructure/validation-webhook-akash:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: NODE_POOL
          value: "akash: nair"
        volumeMounts:
        - name: certs-volume
          readOnly: true
          mountPath: "/certs"
      volumes:
      - name: certs-volume
        secret:
          secretName: admission-tls
